from __future__ import annotations
import typing
__all__: list[str] = ['SharedMemoryInterface', 'SimulatorMessage']
class SharedMemoryInterface:
    def __init__(self) -> None:
        ...
    def getMessage(self) -> Message | None:
        ...
    def putResponse(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> bool:
        ...
class SimulatorMessage:
    def __init__(self) -> None:
        ...
    @property
    def board(self) -> int:
        ...
    @board.setter
    def board(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    @id.setter
    def id(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def moves(self) -> int:
        ...
    @moves.setter
    def moves(self, arg0: typing.SupportsInt) -> None:
        ...
