from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['Message', 'SharedMemoryInterface']
class Message:
    fresh: bool
    def __init__(self) -> None:
        ...
    @property
    def board(self) -> int:
        ...
    @board.setter
    def board(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def id(self) -> int:
        ...
    @id.setter
    def id(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def moves(self) -> int:
        ...
    @moves.setter
    def moves(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def reward(self) -> float:
        ...
    @reward.setter
    def reward(self, arg0: typing.SupportsFloat) -> None:
        ...
class SharedMemoryInterface:
    def __init__(self) -> None:
        ...
    def getMessage(self, arg0: typing.SupportsInt) -> Message:
        ...
    def getMessageBatch(self) -> numpy.typing.NDArray[numpy.int8]:
        ...
    def putResponse(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> bool:
        ...
